language: python
python:
    - "2.7"
    - "3.5"
env:
    - DJANGO_VERSION=1.11
    - DJANGO_VERSION=2.0
install: pip install Django==$DJANGO_VERSION
script: django-admin.py test --settings=test_settings --pythonpath=.
notifications:
    email:
        - dev@jamesturk.net
