language: python
dist: xenial
python:
    - "3.6"
    - "3.7"
env:
    - DJANGO_VERSION=2.2
install: pip install Django==$DJANGO_VERSION flake8
script:
    - django-admin.py test --settings=test_settings --pythonpath=.
    - flake8
notifications:
    email:
        - dev@jamesturk.net
